PROG_DAEMONIZE = False
SRV_PORT = 10002

DEBUG_LOG = None    # None or True
LOG_FILE_LOCATION = None
LOG_FILE_NAME = None
LOG_FILE_LOCATIONS_CLIENTS = None
#spot_sensor.log"

PDI_FILE_SENSOR = '/tmp/spot_sensor.pid'


SPOT_SENSOR = {}
AUTO_DISCOVERY = None
SLEEP_TIMER = None
SLEEP_TIMER_IN = None
SLEEP_TIMER_OUT = 10
MAX_TIME_NOT_SEEN = None
SENSOR_AVAILABLE = None

IP_CCU = None
CCU_CONNECTION_OK = None

PDI_FILE = '/tmp/spot_check.pid'

PROG_DIR = "/opt/spot"
CFG = None

PIFACECAD_SUPPORT = None

RGBLED_SUPPORT = None
RGBLED_RED = None
RGBLED_GREEN = None
RGBLED_BLUE = None

BT_SUPPORT = True

SYS_ENCODING = None
ABS_PATH = None
DB_FILE = None
